export const enum AnalyticsEvent {
    loginPageEntered = "loginPageEntered",
    registrationPageEntered = "registrationPageEntered",
    loginButtonClicked = "loginButtonClicked",
    registrationButtonClicked = "reregistrationButtonClicked",
    successfulLogin = "successfulLogin",
    successfulRegistration = "successfulRegistration",
    jobOfferClicked = "jobOfferClicked",
    postJobOfferButtonClicked = "postJobOfferButtonClicked",
    companyCreationPageEntered = "companyCreationPageEntered",
    companyCreationButtonClicked = "companyCreationButtonClicked",
    successfulCompanyCreation = "successfulCompanyCreation",
    companyUpdatePageEntered ="companyUpdatePageEntered",
    companyUpdateButtonClicked ="companyUpdateButtonClicked",
    successfulCompanyUpdate="successfulCompanyUpdate",
}