export const enum AnalyticsEvent {
    loginPageEntered = "loginPageEntered",
    registrationPageEntered = "registrationPageEntered",
    loginButtonClicked = "loginButtonClicked",
    registrationButtonClicked = "reregistrationButtonClicked",
    successfulLogin = "successfulLogin",
    successfulRegistration = "successfulRegistration",
    jobOfferClicked = "jobOfferClicked",
    postJobOfferButtonClicked = "postJobOfferButtonClicked",
    companyCreationPageEntered = "companyCreationPageEntered",
    findJobOfferPageEntered = "findJobOfferPageEntered",
    jobOfferDetailEntered="jobOfferDetailEntered",
    companyCreationButtonClicked = "companyCreationButtonClicked",
    successfulCompanyCreation = "successfulCompanyCreation",
    companyUpdatePageEntered = "companyUpdatePageEntered",
    companyUpdateButtonClicked = "companyUpdateButtonClicked",
    successfulCompanyUpdate = "successfulCompanyUpdate",
    userAccountPageEntered = "userAccountPageEntered",
    myJobsPageEntered="myJobsPageEntered",
    mySavedJobsPageEntered="mySavedJobsPageEntered",
    userUpdateButtonClicked = "userUpdateButtonClicked",
    successfulUserInfoUpdate = "successfulUserInfoUpdate",
    changePasswordButtonClicked = "changePasswordButtonClicked",
    successfulPasswordChange = "successfulPasswordChange",
    jobPostPageEntered = "jobPostPageEntered",
    error = "error",
}